import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { ProjectGrid } from '@/components/projectGrid/projectGrid'
import { AppBarMain } from '@/components/appBarMain/appBarMain'
import { AboutMeBlurb } from '@/components/aboutMeBlurb/aboutMeBlurb'
// import { Introduction } from '@/components/introduction/introduction'
import AboutMePage from './aboutMe'
import PageIntroduction from './introduction'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar.ico" />
      </Head>
      <main className={styles.main}>
        <PageIntroduction />
      </main>
    </>
  )
}