import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Introduction from '../components/introduction/introduction'
import { Sections } from '../components/sections/sections'
import { Grid, useMediaQuery, useTheme } from '@mui/material'
import { ProjectGrid } from '@/components/projectGrid/projectGrid'
import { useState } from 'react'
import AboutMe from '../components/aboutMe/aboutMe'
import { AppBarMain } from '@/components/appBarMain/appBarMain'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  const [selected, setSelected] = useState('');
  const theme = useTheme();
  const smallScreen = useMediaQuery(theme.breakpoints.down('sm'));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/avatar.ico" />
      </Head>
      <main className={styles.main}>
        <AppBarMain selected={selected} setSelected={setSelected} />
        <Grid container>
          {selected === '' && <Grid item><Introduction /></Grid>}
          {selected === 'portfolio' && <Grid item><ProjectGrid /></Grid>}
          {selected === 'aboutMe' && <Grid item><AboutMe /></Grid>}
          {!smallScreen && <Sections setSelected={setSelected} />}
        </Grid>
      </main>



    </>
  )
}